name: Linting go code

on:
  push:

jobs:

  build:
    name: Check code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.19]
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev npm pkg-config libfuse-dev -y
  
      - name: Build assets
        run: |
          npm install --prefix frontend
          npm run build --prefix frontend

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: v1.50
          args: -E bodyclose,gocritic,gofmt,gosec,govet,nestif,nlreturn,revive,rowserrcheck --exclude G401,G501,G107 --timeout=10m
          skip-pkg-cache: true
