name: Linting go code

on:
  push:

jobs:

  build:
    name: Check code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.19]
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install mesa-common-dev libpulse-mainloop-glib0 libpulse0 libfuse-dev -y

      - name: Install GUI dependencies
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: |
          bash ./dev_utils/setup-linux.sh
  
      - name: Build desktop
        run: |
          qtdeploy build desktop cmd/qt/

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          version: v1.50
          args: -E bodyclose,gocritic,gofmt,gosec,govet,nestif,nlreturn,revive,rowserrcheck --exclude G401,G501,G107 --skip-files cmd/qt/moc.go,cmd/qt/main.go,cmd/qt/logmodel.go,cmd/qt/projectmodel.go  --timeout=10m
          skip-pkg-cache: true
